version: '3.8'

services:
  evpower-mobile:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=https://ocpp.evpower.kg/api
    stdin_open: true
    tty: true